### ISSUE TITLE
Multiple wallpaper created while open/close multiple time

### ISSUE THREAD

**Issue by TanvirM** [hiroprotagonist/jquery.mobile.actionsheet#6] opened 2011-06-29 08:17 UTC
JQM version: 1.0b1

Issue: After open and close first time, on the second time the box is not closed properly. 

Reason: In the open function the wallpaper DIV append with jqm-content. This append content stored in the hash history, after hit the close button second time the immediate wallpaper div removed but the one from history stays on. 

Solve: Create the wallpaper at initiation and keep it hidden [Check the changes on my fork.]

**Comment by hiroprotagonist** [comment] 2011-06-30 14:11
Hey Tanvir

Its hard to find your changes since your editor changed every tab into 4 whitespaces on every line. I know that almost everybody use spaces instead of tabs. crazy world. please tell me wich lines you changed.

**Comment by hiroprotagonist** [comment] 2011-06-30 14:27
Again... 
I cannot reproduce your issue. I am opening and closing the sheet several times. The DOM still gets cleaned up and the wallpaper gets removed. Can you please post your test markup.

Regards
Stean

**Comment by TanvirM** [comment] 2011-06-30 14:27
Sorry about that, I'm a bit of old school, steel use notepad++, anyway

on this file https://github.com/TanvirM/jquery.mobile.actionsheet/blob/de22c1bdd469679b3c82c7b12a89caf1ad660f0b/jquery.mobile.actionsheet.js

look for following lines

Line 31 - 37
Line 61 - 66
Line 70, 89, 100, 109

**Comment by TanvirM** [comment] 2011-06-30 14:42
This might help...

<ul>
...
<li data-role="actionsheet" data-sheet="action_1">
<a href="#" id="option_l1">
<h3>Option Tile</h3>
<p>Option Desc</p>
</a>
</li>
<div id="action_1">
<div data-role="header" data-theme="d" data-position="inline"
data-backbtn="false">
<h1>Action Title</h1>
</div>
<div data-role="content" data-theme="c">
<div data-role="fieldcontain" class="modalinput">
<label for="add_info">Lebel:</label>
<input type="text" name="add_info" id="add_info" class="modalText" />
</div>
<div class="modalbtn">
<a data-inline="true" data-role="button" href="/path" data-theme="c"
id="add_info_btn" rel="external">Next</a>
<a data-inline="true" data-role="button" data-rel="close" href="#"
data-theme="d">Cancel</a>
</div>
</div>
</div>
...
</ul>


T

On Thu, Jun 30, 2011 at 8:27 PM, hiroprotagonist <
reply@reply.github.com>wrote:

> Again...
> I cannot reproduce your issue. I am opening and closing the sheet several
> times. The DOM still gets cleaned up and the wallpaper gets removed. Can you
> please post your test markup.
> 
> Regards
> Stean
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/hiroprotagonist/jquery.mobile.actionsheet/issues/6#issuecomment-1475162

## 

---

Tanvir M. Shuvo
- (880) 167 167 5652

**Comment by hiroprotagonist** [comment] 2011-07-21 20:35
Ahoi Tanvir!
Im sorry but i cannot reproduce the behavior. I am closing this issue and i hope that you still enjoy working with actionsheet.

Cheers
Stefan

**Closed as completed by hiroprotagonist** 2011-07-21 20:35 UTC

**Comment by TanvirM** [comment] 2011-07-22 02:44
Hi Stefan,

Sure you can close the issue... it's probably because of my complex 
integration. Thanks again  for your work on actionsheet.

Cheers

On 7/22/2011 2:35 AM, hiroprotagonist wrote:

> Ahoi Tanvir!
> Im sorry but i cannot reproduce the behavior. I am closing this issue and i hope that you still enjoy working with actionsheet.
> 
> Cheers
> Stefan

## 

Tanvir M. Shuvo
+880 167 1675652
